services:
  ca:
    image: ghcr.io/eeymoo/open-hr-agent-ca:main
    container_name: ca-example
    restart: unless-stopped
    environment:
      - PORT=4096
      - NODE_ENV=production
    networks:
      - hr-network

networks:
  hr-network:
    external: true
